const actions = {
    START_NEW_GAME : "START_NEW_GAME",
    FROM_DECK_TO_PLAYER : "FROM_DECK_TO_PLAYER",
    FROM_DISCARD_TO_PLAYER : "FROM_DISCARD_TO_PLAYER",
    SELECT_CARD_FROM_HAND : "SELECT_CARD_FROM_HAND",
    FROM_HAND_TO_DISCARD : "FROM_HAND_TO_DISCARD",
    AI_PICKED_FROM_DECK : "AI_PICKED_FROM_DECK",
    AI_PICKED_FROM_DISCARD : "AI_PICKED_FROM_DISCARD",
    AI_WAIT_ONE_COMPLETE : "AI_WAIT_ONE_COMPLETE",
    AI_DRAW_OOT : "AI_DRAW_OOT",
    AI_WAIT_TWO_COMPLETE : "AI_WAIT_TWO_COMPLETE",
    DRAW_OOT_RESOLVE : "DRAW_OOT_RESOLVE",
    FROM_AI_TO_DISCARD : "FROM_AI_TO_DISCARD",
    SORT_PLAYER_HAND : "SORT_PLAYER_HAND",
    SHOW_GOING_DOWN_MODAL : "SHOW_GOING_DOWN_MODAL",
    CANCEL_PLAYER_GO_DOWN : "CANCEL_PLAYER_GO_DOWN",
    GO_DOWN_SELECT_CARD : "GO_DOWN_SELECT_CARD",
    GO_DOWN_SUBMIT_SETRUN : "GO_DOWN_SUBMIT_SETRUN",
    TEMPLATE : "TEMPLATE"
}

export default actions



