const actions = {
    START_NEW_GAME : "START_NEW_GAME",
    FROM_DECK_TO_PLAYER : "FROM_DECK_TO_PLAYER",
    FROM_DISCARD_TO_PLAYER : "FROM_DISCARD_TO_PLAYER",
    SELECT_CARD_FROM_HAND : "SELECT_CARD_FROM_HAND",
    FROM_HAND_TO_DISCARD : "FROM_HAND_TO_DISCARD",
    AI_PICKED_FROM_DECK : "AI_PICKED_FROM_DECK",
    TEMPLATE : "TEMPLATE"
}

export default actions